version: '3.8'

services:
  reports-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reports-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - VOTES_SERVICE_URL=http://votes-service:8083
      - USERS_SERVICE_URL=http://users-service:8082
      - AUTH_SERVICE_URL=http://auth-service:8081
      - JWT_SECRET=mySecretKey
      - JWT_EXPIRATION=86400000
    networks:
      - voting-network
    depends_on:
      - votes-service
      - users-service
      - auth-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Servicios externos (referencias para desarrollo)
  votes-service:
    image: votes-service:latest
    container_name: votes-service
    ports:
      - "8083:8083"
    networks:
      - voting-network
    # Configuración específica del votes-service aquí

  users-service:
    image: users-service:latest
    container_name: users-service
    ports:
      - "8082:8082"
    networks:
      - voting-network
    # Configuración específica del users-service aquí

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - voting-network
    # Configuración específica del auth-service aquí

networks:
  voting-network:
    driver: bridge
    name: voting-network

volumes:
  reports-logs:
    driver: local

