version: '3.8'

services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra-test
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

# Este archivo puede eliminarse o marcarse como obsoleto.
# Toda la configuración de Cassandra está en config/docker/docker-compose.yaml